stages:
  - test
  - build

test:
  stage: test
  image: python:3.7.4
  script:
    - python -m venv venv
    - source venv/bin/activate
    - python -m pip install -U pip
    - make build
    - make black-check
    - make flake8
    - make pytest
  only:
    - master
    - merge_request
    - external_pull_request

build-docker:
  stage: build
  image: docker:19.03.4
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    CONTAINER_IMAGE: ${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}
  script:
    - docker build -t ${CONTAINER_IMAGE} .
  only:
    - master
    - merge_request
    - external_pull_request
