stages:
  - test
  - build

test:
  stage: test
  image: python:3.7.4
  script:
    - python -m venv venv
    - source venv/bin/activate
    - python -m pip install -U pip
    - make build
    - make black-check
    - make flake8
    - make pytest
  only:
    - master
    - merge_request
    - external_pull_request

build-docker:
  stage: build
  image: docker:19.03.4
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    CONTAINER_IMAGE_BUILDER: ${DOCKER_USER}/${CI_PROJECT_NAME}:builder
    CONTAINER_IMAGE_LATEST: ${DOCKER_USER}/${CI_PROJECT_NAME}:latest
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker pull ${CONTAINER_IMAGE_BUILDER} || exit 0
    - docker build --target builder --cache-from ${CONTAINER_IMAGE_BUILDER} -t ${CONTAINER_IMAGE_BUILDER} .
    - docker push ${CONTAINER_IMAGE_BUILDER}
    - docker pull ${CONTAINER_IMAGE_LATEST} || exit 0
    - docker build --cache-from ${CONTAINER_IMAGE_BUILDER} --cache-from ${CONTAINER_IMAGE_LATEST} -t ${CONTAINER_IMAGE_LATEST} .
    - docker push ${CONTAINER_IMAGE_LATEST}
  only:
    - master
    - merge_request
    - external_pull_request
