branches:
  only:
  - master

language: python

services:
  - docker

dist: bionic
python: 3.7

before_install:
  - python -m pip install -U pip

install:
  - make build

script:
  - make black-check
  - make flake8
  - make pytest

before_deploy:
  - docker build -t ${TRAVIS_REPO_SLUG}:latest .
