branches:
  only:
  - master

language: python
dist: bionic
python: 3.7.4

services:
  - docker

env:
  global:
    - CONTAINER_IMAGE_BUILDER=${TRAVIS_REPO_SLUG}:builder
    - CONTAINER_IMAGE_LATEST=${TRAVIS_REPO_SLUG}:latest
    - DOCKER_USER=yxtay

before_install:
  - python -m pip install -U pip

install:
  - make build

script:
  - make black-check
  - make flake8
  - make pytest
  - |
    echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USER} --password-stdin
    docker pull ${CONTAINER_IMAGE_BUILDER} || exit 0
    docker build --target builder --cache-from ${CONTAINER_IMAGE_BUILDER} -t ${CONTAINER_IMAGE_BUILDER} .
    docker push ${CONTAINER_IMAGE_BUILDER}
    docker pull ${CONTAINER_IMAGE_LATEST} || exit 0
    docker build --cache-from ${CONTAINER_IMAGE_BUILDER} --cache-from ${CONTAINER_IMAGE_LATEST} -t ${CONTAINER_IMAGE_LATEST} .
    docker push ${CONTAINER_IMAGE_LATEST}

notifications:
  email:
    on_success: change
    on_failure: always
