steps:
# Deploy an image from Container Registry to Cloud Run
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/$PROJECT_ID/falcon-echo || exit 0
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/falcon-echo', '--cache-from', 'gcr.io/$PROJECT_ID/falcon-echo', '.']
- name: 'gcr.io/$PROJECT_ID/falcon-echo'
  entrypoint: 'bash'
  args:
    - '-c'
    - 'pip install -r requirements-test.txt && pytest -v'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/falcon-echo']
#- name: 'gcr.io/cloud-builders/gcloud'
#  args: ['beta', 'run', 'deploy', 'falcon-echo', '--image', 'gcr.io/$PROJECT_ID/falcon-echo', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
timeout: '600s'
images:
  - 'gcr.io/$PROJECT_ID/falcon-echo'
