steps:
  # test
- name: 'python:${_PYTHON_VERSION}'
  id: 'build-env'
  entrypoint: 'bash'
  args: ['-c', 'make build']
- name: 'python:${_PYTHON_VERSION}'
  id: 'black'
  entrypoint: 'bash'
  args: ['-c', 'make black-check']
- name: 'python:${_PYTHON_VERSION}'
  id: 'flake8'
  entrypoint: 'bash'
  args: ['-c', 'make flake8']
- name: 'python:${_PYTHON_VERSION}'
  id: 'pytest'
  entrypoint: 'bash'
  args: ['-c', 'make pytest']

  # builder
- name: 'gcr.io/cloud-builders/docker'
  id: 'pull-builder'
  entrypoint: 'bash'
  args: ['-c', 'docker pull gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:builder || exit 0']
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-builder'
  args:
    - 'build'
    - '--target'
    - 'builder'
    - '--cache-from'
    - 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:builder'
    - '-t'
    - 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:builder'
    - '.'
  waitFor: ['pull-builder']
- name: 'gcr.io/cloud-builders/docker'
  id: 'push-builder'
  args: ['push', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:builder']
  waitFor: ['build-builder', 'test']

  # latest
- name: 'gcr.io/cloud-builders/docker'
  id: 'pull-latest'
  entrypoint: 'bash'
  args: ['-c', 'docker pull gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:latest || exit 0']
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-latest'
  args:
    - 'build'
    - '--cache-from'
    - 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:builder'
    - '--cache-from'
    - 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:latest'
    - '-t'
    - 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:latest'
    - '.'
  waitFor: ['pull-latest', 'build-builder']
- name: 'gcr.io/cloud-builders/docker'
  id: 'push-latest'
  args: ['push', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:latest']
  waitFor: ['build-latest', 'test']

  # cloud-run
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'cloud-run-deploy'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      [[ "${BRANCH_NAME}" == "master" ]] && gcloud beta run deploy ${_SERVICE_NAME} --image gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:latest --region us-central1 --platform managed --allow-unauthenticated || exit 0
  waitFor: ['push-latest']

timeout: '600s'
substitutions:
  _PYTHON_VERSION: '3.7.4'
  _SERVICE_NAME: 'falcon-echo'
  _IMAGE_NAME: 'falcon-echo'
images:
  - 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}'
