steps:
- name: 'python:3.7.4'
  entrypoint: 'bash'
  args:
    - '-c'
    - 'pip install -r requirements.txt && pip install -r requirements-test.txt && pytest -v'
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - 'docker pull gcr.io/$PROJECT_ID/${_IMAGE_NAME} || exit 0'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}', '--cache-from', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}', '.']
- name: 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}'
  entrypoint: 'bash'
  args:
    - '-c'
    - 'pip install -r requirements-test.txt && pytest -v'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      [[ "$BRANCH_NAME" == "master" ]] && beta run deploy ${_SERVICE_NAME} --image gcr.io/default-223103/${_IMAGE_NAME} --region us-central1 --platform managed --allow-unauthenticated
      [[ "$BRANCH_NAME" != "master" ]] && exit 0
timeout: '600s'
substitutions:
    _SERVICE_NAME: 'falcon-echo'
    _IMAGE_NAME: 'falcon-echo'
images:
  - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}'
