name: pytest

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: pytest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up Python 3.7.4
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Test with pytest
      run: |
        python -m pip install -r requirements-test.txt
        pytest
