name: CI

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: make build
    - name: Run black
      run: make black-check
    - name: Run flake8
      run: make flake8
    - name: Run pytest
      run: make pytest

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    env:
      CONTAINER_IMAGE_BUILDER: ${{ github.repository }}:builder
      CONTAINER_IMAGE_LATEST: ${{ github.repository }}:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Docker login
      run: echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USER} --password-stdin
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USER: yxtay
    - name: Pull builder
      run: docker pull ${CONTAINER_IMAGE_BUILDER} || exit 0
    - name: Build builder
      run: docker build --target builder --cache-from ${CONTAINER_IMAGE_BUILDER} -t ${CONTAINER_IMAGE_BUILDER} .
    - name: Push builder
      run: docker push ${CONTAINER_IMAGE_BUILDER}
    - name: Pull latest
      run: docker pull ${CONTAINER_IMAGE_LATEST} || exit 0
    - name: Build latest
      run: docker build --cache-from ${CONTAINER_IMAGE_BUILDER} --cache-from ${CONTAINER_IMAGE_LATEST} -t ${CONTAINER_IMAGE_LATEST} .
    - name: Push latest
      run: docker push ${CONTAINER_IMAGE_LATEST}
