name: CICD

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Master
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up Python 3.7.4
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.4
    - name: Install dependencies
      run: make build
    - name: black
      run: make black-diff
    - name: flake8
      run: make flake8
    - name: pytest
      run: make pytest
