name: CICD

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  check:
    name: Checks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up Python 3.7.4
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.4
    - name: Install dependencies
      run: make build
    - name: black
      run: make black-check
    - name: flake8
      run: make flake8
    - name: pytest
      run: make pytest

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build -t ${{ github.repository }}:latest .
